[package]
name = "glfw-rs"
version = "0.1.2"
edition = "2024"
readme = "../README.md"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "graphics"]
description = "A rust wrapper for the GLFW library"

[dependencies]
glfw-rs-sys = "1.0.0"

[dev-dependencies]
gl = "0.14.0"
