[package]
name = "glfw-rs-sys"
edition = "2024"
version = "1.0.0"
readme = "../README.md"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "graphics"]
repository = "https://github.com/eliseydudin/glfw"

[build-dependencies]
bindgen = "0.71.1"
pkg-config = "0.3.32"
